/**
 * OmniView Excalidraw 预置模板库 (Starter Templates)
 * 提供云原生架构图、UI 线框原型、流程决策树、思维导图头脑风暴与空白画布
 */

export interface ExcalidrawTemplate {
  id: string;
  name: string;
  nameEn: string;
  description: string;
  descriptionEn: string;
  category: 'architecture' | 'wireframe' | 'flowchart' | 'mindmap' | 'blank';
  data: {
    type: string;
    version: number;
    source: string;
    elements: any[];
    appState?: {
      viewBackgroundColor?: string;
      gridSize?: number | null;
    };
    files?: Record<string, any>;
  };
}

export const EXCALIDRAW_TEMPLATES: ExcalidrawTemplate[] = [
  {
    id: 'architecture',
    name: '云原生微服务架构',
    nameEn: 'Cloud Microservices Architecture',
    description: 'API 网关、认证鉴权、业务微服务与数据库缓存拓扑',
    descriptionEn: 'API Gateway, Auth, Microservices, Database & Cache topology',
    category: 'architecture',
    data: {
      type: 'excalidraw',
      version: 2,
      source: 'https://omniview.dev',
      elements: [
        // 客户端
        {
          id: 'client_box',
          type: 'rectangle',
          x: 60,
          y: 180,
          width: 140,
          height: 80,
          strokeColor: '#3b82f6',
          backgroundColor: '#dbeafe',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 101,
        },
        {
          id: 'client_text',
          type: 'text',
          x: 85,
          y: 205,
          width: 90,
          height: 30,
          text: 'Client App\n(Web / Mobile)',
          fontSize: 14,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#1e40af',
          version: 1,
          versionNonce: 102,
        },
        // 网关
        {
          id: 'gateway_box',
          type: 'rectangle',
          x: 280,
          y: 160,
          width: 160,
          height: 120,
          strokeColor: '#f59e0b',
          backgroundColor: '#fef3c7',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 103,
        },
        {
          id: 'gateway_text',
          type: 'text',
          x: 305,
          y: 205,
          width: 110,
          height: 30,
          text: 'API Gateway\n(Rate Limit & SSL)',
          fontSize: 14,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#b45309',
          version: 1,
          versionNonce: 104,
        },
        // 连线 1
        {
          id: 'arrow_client_gw',
          type: 'arrow',
          x: 200,
          y: 220,
          width: 80,
          height: 0,
          points: [[0, 0], [80, 0]],
          strokeColor: '#64748b',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 105,
        },
        // 认证服务
        {
          id: 'auth_box',
          type: 'rectangle',
          x: 520,
          y: 80,
          width: 150,
          height: 70,
          strokeColor: '#10b981',
          backgroundColor: '#d1fae5',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 106,
        },
        {
          id: 'auth_text',
          type: 'text',
          x: 540,
          y: 100,
          width: 110,
          height: 30,
          text: 'Auth Service\n(OAuth / JWT)',
          fontSize: 14,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#065f46',
          version: 1,
          versionNonce: 107,
        },
        // 核心微服务
        {
          id: 'core_svc_box',
          type: 'rectangle',
          x: 520,
          y: 190,
          width: 150,
          height: 70,
          strokeColor: '#8b5cf6',
          backgroundColor: '#ede9fe',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 108,
        },
        {
          id: 'core_svc_text',
          type: 'text',
          x: 545,
          y: 210,
          width: 100,
          height: 30,
          text: 'Order Service\n(Business Logic)',
          fontSize: 14,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#5b21b6',
          version: 1,
          versionNonce: 109,
        },
        // 数据存储
        {
          id: 'db_box',
          type: 'rectangle',
          x: 740,
          y: 190,
          width: 140,
          height: 70,
          strokeColor: '#ec4899',
          backgroundColor: '#fce7f3',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 110,
        },
        {
          id: 'db_text',
          type: 'text',
          x: 755,
          y: 210,
          width: 110,
          height: 30,
          text: 'PostgreSQL DB\n& Redis Cache',
          fontSize: 14,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#9d174d',
          version: 1,
          versionNonce: 111,
        },
        // 连线
        {
          id: 'arrow_gw_auth',
          type: 'arrow',
          x: 440,
          y: 200,
          width: 80,
          height: -80,
          points: [[0, 0], [80, -80]],
          strokeColor: '#64748b',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 112,
        },
        {
          id: 'arrow_gw_order',
          type: 'arrow',
          x: 440,
          y: 225,
          width: 80,
          height: 0,
          points: [[0, 0], [80, 0]],
          strokeColor: '#64748b',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 113,
        },
        {
          id: 'arrow_order_db',
          type: 'arrow',
          x: 670,
          y: 225,
          width: 70,
          height: 0,
          points: [[0, 0], [70, 0]],
          strokeColor: '#64748b',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 114,
        },
      ],
      appState: {
        viewBackgroundColor: '#ffffff',
        gridSize: 20,
      },
    },
  },
  {
    id: 'flowchart',
    name: '决策流程逻辑图',
    nameEn: 'Flowchart & Decision Tree',
    description: '标准起止、判断菱形与分支执行路径',
    descriptionEn: 'Start/End, Condition Diamond & Branching Paths',
    category: 'flowchart',
    data: {
      type: 'excalidraw',
      version: 2,
      source: 'https://omniview.dev',
      elements: [
        // 开始节点
        {
          id: 'start_ellipse',
          type: 'ellipse',
          x: 200,
          y: 80,
          width: 140,
          height: 60,
          strokeColor: '#10b981',
          backgroundColor: '#d1fae5',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 201,
        },
        {
          id: 'start_text',
          type: 'text',
          x: 235,
          y: 100,
          width: 70,
          height: 20,
          text: '开始 (Start)',
          fontSize: 16,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#065f46',
          version: 1,
          versionNonce: 202,
        },
        // 箭头向下
        {
          id: 'arrow_down_1',
          type: 'arrow',
          x: 270,
          y: 140,
          width: 0,
          height: 60,
          points: [[0, 0], [0, 60]],
          strokeColor: '#64748b',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 203,
        },
        // 判断菱形
        {
          id: 'diamond_check',
          type: 'diamond',
          x: 190,
          y: 200,
          width: 160,
          height: 100,
          strokeColor: '#f59e0b',
          backgroundColor: '#fef3c7',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 204,
        },
        {
          id: 'diamond_text',
          type: 'text',
          x: 220,
          y: 240,
          width: 100,
          height: 20,
          text: '校验合法？',
          fontSize: 15,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#b45309',
          version: 1,
          versionNonce: 205,
        },
        // 成功分支
        {
          id: 'arrow_success',
          type: 'arrow',
          x: 270,
          y: 300,
          width: 0,
          height: 70,
          points: [[0, 0], [0, 70]],
          strokeColor: '#10b981',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 206,
        },
        {
          id: 'text_yes',
          type: 'text',
          x: 280,
          y: 320,
          width: 30,
          height: 20,
          text: '是 (Yes)',
          fontSize: 13,
          fontFamily: 1,
          strokeColor: '#10b981',
          version: 1,
          versionNonce: 207,
        },
        // 成功处理框
        {
          id: 'process_box',
          type: 'rectangle',
          x: 190,
          y: 370,
          width: 160,
          height: 70,
          strokeColor: '#3b82f6',
          backgroundColor: '#dbeafe',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 208,
        },
        {
          id: 'process_text',
          type: 'text',
          x: 215,
          y: 395,
          width: 110,
          height: 20,
          text: '执行持久化存储',
          fontSize: 14,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#1e40af',
          version: 1,
          versionNonce: 209,
        },
      ],
      appState: {
        viewBackgroundColor: '#ffffff',
        gridSize: 20,
      },
    },
  },
  {
    id: 'mindmap',
    name: '思维导图与头脑风暴',
    nameEn: 'Mindmap & Brainstorming',
    description: '核心主题与多维发散便签卡片',
    descriptionEn: 'Central Topic & Branching Sticky Notes',
    category: 'mindmap',
    data: {
      type: 'excalidraw',
      version: 2,
      source: 'https://omniview.dev',
      elements: [
        // 中心主题
        {
          id: 'mindmap_center',
          type: 'rectangle',
          x: 300,
          y: 200,
          width: 180,
          height: 80,
          strokeColor: '#6366f1',
          backgroundColor: '#e0e7ff',
          fillStyle: 'solid',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 301,
        },
        {
          id: 'center_text',
          type: 'text',
          x: 325,
          y: 225,
          width: 130,
          height: 30,
          text: '核心规划目标\nCore Goal',
          fontSize: 16,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#3730a3',
          version: 1,
          versionNonce: 302,
        },
        // 分支 1: 用户体验
        {
          id: 'branch_1',
          type: 'rectangle',
          x: 80,
          y: 100,
          width: 140,
          height: 60,
          strokeColor: '#f43f5e',
          backgroundColor: '#ffe4e6',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 303,
        },
        {
          id: 'branch_1_text',
          type: 'text',
          x: 100,
          y: 120,
          width: 100,
          height: 20,
          text: '🎨 极致交互体验',
          fontSize: 14,
          fontFamily: 1,
          strokeColor: '#9f1239',
          version: 1,
          versionNonce: 304,
        },
        // 连线 1
        {
          id: 'arrow_branch_1',
          type: 'arrow',
          x: 300,
          y: 220,
          width: -80,
          height: -70,
          points: [[0, 0], [-80, -70]],
          strokeColor: '#f43f5e',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 305,
        },
        // 分支 2: 高性能引擎
        {
          id: 'branch_2',
          type: 'rectangle',
          x: 560,
          y: 100,
          width: 140,
          height: 60,
          strokeColor: '#059669',
          backgroundColor: '#d1fae5',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 306,
        },
        {
          id: 'branch_2_text',
          type: 'text',
          x: 580,
          y: 120,
          width: 100,
          height: 20,
          text: '⚡ 毫秒响应与缓存',
          fontSize: 14,
          fontFamily: 1,
          strokeColor: '#065f46',
          version: 1,
          versionNonce: 307,
        },
        // 连线 2
        {
          id: 'arrow_branch_2',
          type: 'arrow',
          x: 480,
          y: 220,
          width: 80,
          height: -70,
          points: [[0, 0], [80, -70]],
          strokeColor: '#059669',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 308,
        },
      ],
      appState: {
        viewBackgroundColor: '#ffffff',
        gridSize: 20,
      },
    },
  },
  {
    id: 'blank',
    name: '空白白板',
    nameEn: 'Blank Canvas',
    description: '初始空画布，自由绘制',
    descriptionEn: 'Start from scratch with a fresh canvas',
    category: 'blank',
    data: {
      type: 'excalidraw',
      version: 2,
      source: 'https://omniview.dev',
      elements: [],
      appState: {
        viewBackgroundColor: '#ffffff',
        gridSize: 20,
      },
    },
  },
];
