/**
 * OmniView Excalidraw 预置模板库 (Starter Templates)
 * 提供云原生架构图、UI 线框原型、流程决策树、思维导图头脑风暴与空白画布
 */

export interface ExcalidrawTemplate {
  id: string;
  name: string;
  nameEn: string;
  description: string;
  descriptionEn: string;
  category: 'architecture' | 'wireframe' | 'flowchart' | 'mindmap' | 'blank';
  data: {
    type: string;
    version: number;
    source: string;
    elements: any[];
    appState?: {
      viewBackgroundColor?: string;
      gridSize?: number | null;
    };
    files?: Record<string, any>;
  };
}

export const EXCALIDRAW_TEMPLATES: ExcalidrawTemplate[] = [
  {
    id: 'architecture',
    name: '云原生微服务架构',
    nameEn: 'Cloud Microservices Architecture',
    description: 'API 网关、认证鉴权、业务微服务与数据库缓存拓扑',
    descriptionEn: 'API Gateway, Auth, Microservices, Database & Cache topology',
    category: 'architecture',
    data: {
      type: 'excalidraw',
      version: 2,
      source: 'https://omniview.dev',
      elements: [
        // 客户端
        {
          id: 'client_box',
          type: 'rectangle',
          x: 60,
          y: 180,
          width: 140,
          height: 80,
          strokeColor: '#3b82f6',
          backgroundColor: '#dbeafe',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 101,
        },
        {
          id: 'client_text',
          type: 'text',
          x: 85,
          y: 205,
          width: 90,
          height: 30,
          text: 'Client App\n(Web / Mobile)',
          fontSize: 14,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#1e40af',
          version: 1,
          versionNonce: 102,
        },
        // 网关
        {
          id: 'gateway_box',
          type: 'rectangle',
          x: 280,
          y: 160,
          width: 160,
          height: 120,
          strokeColor: '#f59e0b',
          backgroundColor: '#fef3c7',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 103,
        },
        {
          id: 'gateway_text',
          type: 'text',
          x: 305,
          y: 205,
          width: 110,
          height: 30,
          text: 'API Gateway\n(Rate Limit & SSL)',
          fontSize: 14,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#b45309',
          version: 1,
          versionNonce: 104,
        },
        // 连线 1
        {
          id: 'arrow_client_gw',
          type: 'arrow',
          x: 200,
          y: 220,
          width: 80,
          height: 0,
          points: [[0, 0], [80, 0]],
          strokeColor: '#64748b',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 105,
        },
        // 认证服务
        {
          id: 'auth_box',
          type: 'rectangle',
          x: 520,
          y: 80,
          width: 150,
          height: 70,
          strokeColor: '#10b981',
          backgroundColor: '#d1fae5',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 106,
        },
        {
          id: 'auth_text',
          type: 'text',
          x: 540,
          y: 100,
          width: 110,
          height: 30,
          text: 'Auth Service\n(OAuth / JWT)',
          fontSize: 14,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#065f46',
          version: 1,
          versionNonce: 107,
        },
        // 核心微服务
        {
          id: 'core_svc_box',
          type: 'rectangle',
          x: 520,
          y: 190,
          width: 150,
          height: 70,
          strokeColor: '#8b5cf6',
          backgroundColor: '#ede9fe',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 108,
        },
        {
          id: 'core_svc_text',
          type: 'text',
          x: 545,
          y: 210,
          width: 100,
          height: 30,
          text: 'Order Service\n(Business Logic)',
          fontSize: 14,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#5b21b6',
          version: 1,
          versionNonce: 109,
        },
        // 数据存储
        {
          id: 'db_box',
          type: 'rectangle',
          x: 740,
          y: 190,
          width: 140,
          height: 70,
          strokeColor: '#ec4899',
          backgroundColor: '#fce7f3',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 110,
        },
        {
          id: 'db_text',
          type: 'text',
          x: 755,
          y: 210,
          width: 110,
          height: 30,
          text: 'PostgreSQL DB\n& Redis Cache',
          fontSize: 14,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#9d174d',
          version: 1,
          versionNonce: 111,
        },
        // 连线
        {
          id: 'arrow_gw_auth',
          type: 'arrow',
          x: 440,
          y: 200,
          width: 80,
          height: -80,
          points: [[0, 0], [80, -80]],
          strokeColor: '#64748b',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 112,
        },
        {
          id: 'arrow_gw_order',
          type: 'arrow',
          x: 440,
          y: 225,
          width: 80,
          height: 0,
          points: [[0, 0], [80, 0]],
          strokeColor: '#64748b',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 113,
        },
        {
          id: 'arrow_order_db',
          type: 'arrow',
          x: 670,
          y: 225,
          width: 70,
          height: 0,
          points: [[0, 0], [70, 0]],
          strokeColor: '#64748b',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 114,
        },
      ],
      appState: {
        viewBackgroundColor: '#ffffff',
        gridSize: 20,
      },
    },
  },
  {
    id: 'flowchart',
    name: '决策流程逻辑图',
    nameEn: 'Flowchart & Decision Tree',
    description: '标准起止、判断菱形与分支执行路径',
    descriptionEn: 'Start/End, Condition Diamond & Branching Paths',
    category: 'flowchart',
    data: {
      type: 'excalidraw',
      version: 2,
      source: 'https://omniview.dev',
      elements: [
        // 开始节点
        {
          id: 'start_ellipse',
          type: 'ellipse',
          x: 200,
          y: 80,
          width: 140,
          height: 60,
          strokeColor: '#10b981',
          backgroundColor: '#d1fae5',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 201,
        },
        {
          id: 'start_text',
          type: 'text',
          x: 235,
          y: 100,
          width: 70,
          height: 20,
          text: '开始 (Start)',
          fontSize: 16,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#065f46',
          version: 1,
          versionNonce: 202,
        },
        // 箭头向下
        {
          id: 'arrow_down_1',
          type: 'arrow',
          x: 270,
          y: 140,
          width: 0,
          height: 60,
          points: [[0, 0], [0, 60]],
          strokeColor: '#64748b',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 203,
        },
        // 判断菱形
        {
          id: 'diamond_check',
          type: 'diamond',
          x: 190,
          y: 200,
          width: 160,
          height: 100,
          strokeColor: '#f59e0b',
          backgroundColor: '#fef3c7',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 204,
        },
        {
          id: 'diamond_text',
          type: 'text',
          x: 220,
          y: 240,
          width: 100,
          height: 20,
          text: '校验合法？',
          fontSize: 15,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#b45309',
          version: 1,
          versionNonce: 205,
        },
        // 成功分支
        {
          id: 'arrow_success',
          type: 'arrow',
          x: 270,
          y: 300,
          width: 0,
          height: 70,
          points: [[0, 0], [0, 70]],
          strokeColor: '#10b981',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 206,
        },
        {
          id: 'text_yes',
          type: 'text',
          x: 280,
          y: 320,
          width: 30,
          height: 20,
          text: '是 (Yes)',
          fontSize: 13,
          fontFamily: 1,
          strokeColor: '#10b981',
          version: 1,
          versionNonce: 207,
        },
        // 成功处理框
        {
          id: 'process_box',
          type: 'rectangle',
          x: 190,
          y: 370,
          width: 160,
          height: 70,
          strokeColor: '#3b82f6',
          backgroundColor: '#dbeafe',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 208,
        },
        {
          id: 'process_text',
          type: 'text',
          x: 215,
          y: 395,
          width: 110,
          height: 20,
          text: '执行持久化存储',
          fontSize: 14,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#1e40af',
          version: 1,
          versionNonce: 209,
        },
      ],
      appState: {
        viewBackgroundColor: '#ffffff',
        gridSize: 20,
      },
    },
  },
  {
    id: 'mindmap',
    name: '思维导图与头脑风暴',
    nameEn: 'Mindmap & Brainstorming',
    description: '核心主题与多维发散便签卡片',
    descriptionEn: 'Central Topic & Branching Sticky Notes',
    category: 'mindmap',
    data: {
      type: 'excalidraw',
      version: 2,
      source: 'https://omniview.dev',
      elements: [
        // 中心主题
        {
          id: 'mindmap_center',
          type: 'rectangle',
          x: 300,
          y: 200,
          width: 180,
          height: 80,
          strokeColor: '#6366f1',
          backgroundColor: '#e0e7ff',
          fillStyle: 'solid',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 301,
        },
        {
          id: 'center_text',
          type: 'text',
          x: 325,
          y: 225,
          width: 130,
          height: 30,
          text: '核心规划目标\nCore Goal',
          fontSize: 16,
          fontFamily: 1,
          textAlign: 'center',
          strokeColor: '#3730a3',
          version: 1,
          versionNonce: 302,
        },
        // 分支 1: 用户体验
        {
          id: 'branch_1',
          type: 'rectangle',
          x: 80,
          y: 100,
          width: 140,
          height: 60,
          strokeColor: '#f43f5e',
          backgroundColor: '#ffe4e6',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 303,
        },
        {
          id: 'branch_1_text',
          type: 'text',
          x: 100,
          y: 120,
          width: 100,
          height: 20,
          text: '🎨 极致交互体验',
          fontSize: 14,
          fontFamily: 1,
          strokeColor: '#9f1239',
          version: 1,
          versionNonce: 304,
        },
        // 连线 1
        {
          id: 'arrow_branch_1',
          type: 'arrow',
          x: 300,
          y: 220,
          width: -80,
          height: -70,
          points: [[0, 0], [-80, -70]],
          strokeColor: '#f43f5e',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 305,
        },
        // 分支 2: 高性能引擎
        {
          id: 'branch_2',
          type: 'rectangle',
          x: 560,
          y: 100,
          width: 140,
          height: 60,
          strokeColor: '#059669',
          backgroundColor: '#d1fae5',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          version: 1,
          versionNonce: 306,
        },
        {
          id: 'branch_2_text',
          type: 'text',
          x: 580,
          y: 120,
          width: 100,
          height: 20,
          text: '⚡ 毫秒响应与缓存',
          fontSize: 14,
          fontFamily: 1,
          strokeColor: '#065f46',
          version: 1,
          versionNonce: 307,
        },
        // 连线 2
        {
          id: 'arrow_branch_2',
          type: 'arrow',
          x: 480,
          y: 220,
          width: 80,
          height: -70,
          points: [[0, 0], [80, -70]],
          strokeColor: '#059669',
          strokeWidth: 2,
          roughness: 1,
          version: 1,
          versionNonce: 308,
        },
      ],
      appState: {
        viewBackgroundColor: '#ffffff',
        gridSize: 20,
      },
    },
  },
  {
    id: 'blank',
    name: '空白白板',
    nameEn: 'Blank Canvas',
    description: '初始空画布，自由绘制',
    descriptionEn: 'Start from scratch with a fresh canvas',
    category: 'blank',
    data: {
      type: 'excalidraw',
      version: 2,
      source: 'https://omniview.dev',
      elements: [],
      appState: {
        viewBackgroundColor: '#ffffff',
        gridSize: 20,
      },
    },
  },
  {
    id: 'k8s-presentation',
    name: '云原生与多Frame演播汇报',
    nameEn: 'Cloud Native & Slide Frames Presentation',
    description: '内置 3 阶段 Frame 画框，支持一键启动 Prezi 式沉浸运镜导览',
    descriptionEn: 'Pre-configured with 3 presentation frames for smooth camera walkthrough',
    category: 'architecture',
    data: {
      type: 'excalidraw',
      version: 2,
      source: 'https://omniview.dev',
      elements: [
        // Frame 1: 请求接入与网关
        {
          id: 'frame-entry',
          type: 'frame',
          name: 'Stage 1: 客户端接入与 API Gateway',
          x: 40,
          y: 60,
          width: 320,
          height: 380,
          strokeColor: '#3b82f6',
          strokeWidth: 2,
          strokeStyle: 'dashed',
          roughness: 0,
          version: 1,
        },
        {
          id: 'client_box_pres',
          type: 'rectangle',
          x: 90,
          y: 120,
          width: 220,
          height: 80,
          strokeColor: '#2563eb',
          backgroundColor: '#dbeafe',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          frameId: 'frame-entry',
          version: 1,
        },
        {
          id: 'client_txt_pres',
          type: 'text',
          x: 120,
          y: 150,
          width: 160,
          height: 25,
          text: '🌐 Web / App 客户端',
          fontSize: 16,
          strokeColor: '#1e40af',
          frameId: 'frame-entry',
          version: 1,
        },
        {
          id: 'gw_box_pres',
          type: 'rectangle',
          x: 90,
          y: 280,
          width: 220,
          height: 90,
          strokeColor: '#7c3aed',
          backgroundColor: '#ede9fe',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          frameId: 'frame-entry',
          version: 1,
        },
        {
          id: 'gw_txt_pres',
          type: 'text',
          x: 110,
          y: 310,
          width: 180,
          height: 30,
          text: '⚡ Envoy / Ingress 网关\n(TLS & 限流防护)',
          fontSize: 14,
          textAlign: 'center',
          strokeColor: '#5b21b6',
          frameId: 'frame-entry',
          version: 1,
        },
        // Frame 2: K8s 容器编排
        {
          id: 'frame-k8s',
          type: 'frame',
          name: 'Stage 2: Kubernetes 核心工作负载 (Pods)',
          x: 420,
          y: 60,
          width: 440,
          height: 380,
          strokeColor: '#059669',
          strokeWidth: 2,
          strokeStyle: 'dashed',
          roughness: 0,
          version: 1,
        },
        {
          id: 'pod_1',
          type: 'rectangle',
          x: 460,
          y: 120,
          width: 170,
          height: 100,
          strokeColor: '#059669',
          backgroundColor: '#d1fae5',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          frameId: 'frame-k8s',
          version: 1,
        },
        {
          id: 'pod_1_txt',
          type: 'text',
          x: 475,
          y: 155,
          width: 140,
          height: 30,
          text: '☸️ Order Service\n(Deployment x3)',
          fontSize: 14,
          textAlign: 'center',
          strokeColor: '#065f46',
          frameId: 'frame-k8s',
          version: 1,
        },
        {
          id: 'pod_2',
          type: 'rectangle',
          x: 660,
          y: 120,
          width: 170,
          height: 100,
          strokeColor: '#059669',
          backgroundColor: '#d1fae5',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          frameId: 'frame-k8s',
          version: 1,
        },
        {
          id: 'pod_2_txt',
          type: 'text',
          x: 675,
          y: 155,
          width: 140,
          height: 30,
          text: '☸️ Payment Pod\n(Deployment x2)',
          fontSize: 14,
          textAlign: 'center',
          strokeColor: '#065f46',
          frameId: 'frame-k8s',
          version: 1,
        },
        {
          id: 'kafka_box',
          type: 'rectangle',
          x: 520,
          y: 280,
          width: 250,
          height: 90,
          strokeColor: '#ea580c',
          backgroundColor: '#ffedd5',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          frameId: 'frame-k8s',
          version: 1,
        },
        {
          id: 'kafka_txt',
          type: 'text',
          x: 540,
          y: 310,
          width: 210,
          height: 30,
          text: '📬 Kafka 事件分发总线\n(High Throughput Stream)',
          fontSize: 14,
          textAlign: 'center',
          strokeColor: '#9a3412',
          frameId: 'frame-k8s',
          version: 1,
        },
        // Frame 3: 数据存储与持久化
        {
          id: 'frame-storage',
          type: 'frame',
          name: 'Stage 3: 分布式存储与多级缓存',
          x: 920,
          y: 60,
          width: 360,
          height: 380,
          strokeColor: '#d97706',
          strokeWidth: 2,
          strokeStyle: 'dashed',
          roughness: 0,
          version: 1,
        },
        {
          id: 'redis_cluster',
          type: 'rectangle',
          x: 960,
          y: 120,
          width: 280,
          height: 90,
          strokeColor: '#dc2626',
          backgroundColor: '#fee2e2',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          frameId: 'frame-storage',
          version: 1,
        },
        {
          id: 'redis_txt',
          type: 'text',
          x: 990,
          y: 150,
          width: 220,
          height: 30,
          text: '⚡ Redis Cluster 缓存层\n(Sub-millisecond Latency)',
          fontSize: 14,
          textAlign: 'center',
          strokeColor: '#991b1b',
          frameId: 'frame-storage',
          version: 1,
        },
        {
          id: 'mysql_cluster',
          type: 'rectangle',
          x: 960,
          y: 280,
          width: 280,
          height: 100,
          strokeColor: '#2563eb',
          backgroundColor: '#eff6ff',
          fillStyle: 'hachure',
          strokeWidth: 2,
          roughness: 1,
          roundness: { type: 3 },
          frameId: 'frame-storage',
          version: 1,
        },
        {
          id: 'mysql_txt',
          type: 'text',
          x: 980,
          y: 310,
          width: 240,
          height: 40,
          text: '🗄️ MySQL 主从复制高可用集群\n(ACID & Raft Consensus)',
          fontSize: 14,
          textAlign: 'center',
          strokeColor: '#1e40af',
          frameId: 'frame-storage',
          version: 1,
        },
      ],
      appState: {
        viewBackgroundColor: '#ffffff',
        gridSize: 20,
      },
    },
  },
];

/**
 * 架构物料图元资产 (Architectural Stencils)
 * 可直接一键插入当前白板视口
 */
export interface ExcalidrawStencil {
  id: string;
  name: string;
  nameEn: string;
  category: 'cloud' | 'compute' | 'storage' | 'network' | 'ui' | 'ai' | 'chart' | 'custom';
  color: string;
  description: string;
  elements: any[];
}

export const EXCALIDRAW_STENCILS: ExcalidrawStencil[] = [
  // --- 1. 计算与容器云 ---
  {
    id: 'k8s-pod',
    name: 'K8s Pod 容器单元',
    nameEn: 'Kubernetes Pod',
    category: 'compute',
    color: '#059669',
    description: '包含副本标签与生命周期声明的标准 Pod',
    elements: [
      {
        id: 'stencil_pod_box',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 160,
        height: 80,
        strokeColor: '#059669',
        backgroundColor: '#d1fae5',
        fillStyle: 'hachure',
        strokeWidth: 2,
        roughness: 1,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_pod_txt',
        type: 'text',
        x: 10,
        y: 28,
        width: 140,
        height: 25,
        text: '☸️ Pod 容器单元',
        fontSize: 14,
        textAlign: 'center',
        strokeColor: '#065f46',
      },
    ],
  },
  {
    id: 'docker-container',
    name: 'Docker 镜像容器',
    nameEn: 'Docker Container',
    category: 'compute',
    color: '#0284c7',
    description: '独立隔离的运行态容器实例',
    elements: [
      {
        id: 'stencil_docker_box',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 170,
        height: 80,
        strokeColor: '#0284c7',
        backgroundColor: '#e0f2fe',
        fillStyle: 'hachure',
        strokeWidth: 2,
        roughness: 1,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_docker_txt',
        type: 'text',
        x: 10,
        y: 28,
        width: 150,
        height: 25,
        text: '🐳 Docker Container',
        fontSize: 14,
        textAlign: 'center',
        strokeColor: '#0369a1',
      },
    ],
  },
  {
    id: 'cloud-gateway',
    name: 'API 网关与路由',
    nameEn: 'Cloud API Gateway',
    category: 'network',
    color: '#7c3aed',
    description: '反向代理、统一鉴权与流控入口',
    elements: [
      {
        id: 'stencil_gw_box',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 180,
        height: 80,
        strokeColor: '#7c3aed',
        backgroundColor: '#ede9fe',
        fillStyle: 'hachure',
        strokeWidth: 2,
        roughness: 1,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_gw_txt',
        type: 'text',
        x: 10,
        y: 28,
        width: 160,
        height: 25,
        text: '⚡ API Gateway',
        fontSize: 15,
        textAlign: 'center',
        strokeColor: '#5b21b6',
      },
    ],
  },
  {
    id: 'cloud-lb',
    name: '负载均衡器 (SLB)',
    nameEn: 'Load Balancer (SLB/Nginx)',
    category: 'network',
    color: '#4f46e5',
    description: '高并发多活负载均衡与健康探针',
    elements: [
      {
        id: 'stencil_lb_box',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 170,
        height: 75,
        strokeColor: '#4f46e5',
        backgroundColor: '#e0e7ff',
        fillStyle: 'hachure',
        strokeWidth: 2,
        roughness: 1,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_lb_txt',
        type: 'text',
        x: 10,
        y: 25,
        width: 150,
        height: 25,
        text: '⚖️ Load Balancer',
        fontSize: 14,
        textAlign: 'center',
        strokeColor: '#3730a3',
      },
    ],
  },
  {
    id: 'client-app',
    name: '客户端 / 终端应用',
    nameEn: 'Client Terminal (Web / Mobile)',
    category: 'network',
    color: '#0284c7',
    description: '浏览器、移动端或 IoT 请求接入发起方',
    elements: [
      {
        id: 'stencil_client_box',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 160,
        height: 75,
        strokeColor: '#0284c7',
        backgroundColor: '#e0f2fe',
        fillStyle: 'hachure',
        strokeWidth: 2,
        roughness: 1,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_client_txt',
        type: 'text',
        x: 10,
        y: 25,
        width: 140,
        height: 25,
        text: '💻 Client App (User)',
        fontSize: 14,
        textAlign: 'center',
        strokeColor: '#0369a1',
      },
    ],
  },
  // --- 2. 存储与数据流 ---
  {
    id: 'db-cluster',
    name: '高可用数据库节点',
    nameEn: 'Database Cluster Node',
    category: 'storage',
    color: '#2563eb',
    description: '分布式持久化或主从复制数据库单元',
    elements: [
      {
        id: 'stencil_db_box',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 170,
        height: 85,
        strokeColor: '#2563eb',
        backgroundColor: '#dbeafe',
        fillStyle: 'hachure',
        strokeWidth: 2,
        roughness: 1,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_db_txt',
        type: 'text',
        x: 10,
        y: 30,
        width: 150,
        height: 25,
        text: '🗄️ Database Node',
        fontSize: 14,
        textAlign: 'center',
        strokeColor: '#1e40af',
      },
    ],
  },
  {
    id: 'redis-cache',
    name: 'Redis 缓存集群',
    nameEn: 'Redis Cache Cluster',
    category: 'storage',
    color: '#dc2626',
    description: '微秒级极速内存键值缓存',
    elements: [
      {
        id: 'stencil_redis_box',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 160,
        height: 75,
        strokeColor: '#dc2626',
        backgroundColor: '#fee2e2',
        fillStyle: 'hachure',
        strokeWidth: 2,
        roughness: 1,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_redis_txt',
        type: 'text',
        x: 10,
        y: 25,
        width: 140,
        height: 25,
        text: '⚡ Redis Cache',
        fontSize: 14,
        textAlign: 'center',
        strokeColor: '#991b1b',
      },
    ],
  },
  {
    id: 'message-queue',
    name: '消息队列 / 事件总线',
    nameEn: 'Message Queue / Bus',
    category: 'network',
    color: '#ea580c',
    description: 'Kafka / RabbitMQ 异步解耦管道',
    elements: [
      {
        id: 'stencil_mq_box',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 180,
        height: 75,
        strokeColor: '#ea580c',
        backgroundColor: '#ffedd5',
        fillStyle: 'hachure',
        strokeWidth: 2,
        roughness: 1,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_mq_txt',
        type: 'text',
        x: 10,
        y: 25,
        width: 160,
        height: 25,
        text: '📬 Event Queue / Bus',
        fontSize: 14,
        textAlign: 'center',
        strokeColor: '#9a3412',
      },
    ],
  },
  {
    id: 'object-storage',
    name: '对象存储桶 (S3/OSS)',
    nameEn: 'Object Storage Bucket (S3/OSS)',
    category: 'storage',
    color: '#0891b2',
    description: '海量非结构化静态资源与多媒体存储',
    elements: [
      {
        id: 'stencil_s3_box',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 180,
        height: 80,
        strokeColor: '#0891b2',
        backgroundColor: '#cffafe',
        fillStyle: 'hachure',
        strokeWidth: 2,
        roughness: 1,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_s3_txt',
        type: 'text',
        x: 10,
        y: 28,
        width: 160,
        height: 25,
        text: '🪣 Object Storage S3',
        fontSize: 14,
        textAlign: 'center',
        strokeColor: '#155e75',
      },
    ],
  },
  // --- 3. 现代 AI 架构与数据管道 ---
  {
    id: 'ai-agent',
    name: 'AI 智能体核心 (Agent Brain)',
    nameEn: 'AI Agent Decision Brain',
    category: 'ai',
    color: '#8b5cf6',
    description: '自主规划、反思、工具调度的大模型核心脑图元',
    elements: [
      {
        id: 'stencil_agent_box',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 190,
        height: 85,
        strokeColor: '#8b5cf6',
        backgroundColor: '#f3e8ff',
        fillStyle: 'hachure',
        strokeWidth: 2,
        roughness: 1,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_agent_txt',
        type: 'text',
        x: 10,
        y: 30,
        width: 170,
        height: 25,
        text: '🧠 AI Agent Brain',
        fontSize: 15,
        textAlign: 'center',
        strokeColor: '#6b21a8',
      },
    ],
  },
  {
    id: 'vector-db',
    name: '向量数据库 (Vector DB)',
    nameEn: 'Vector Database (RAG)',
    category: 'ai',
    color: '#10b981',
    description: '大模型 RAG 检索增强语义嵌入向量存储',
    elements: [
      {
        id: 'stencil_vdb_box',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 180,
        height: 80,
        strokeColor: '#10b981',
        backgroundColor: '#d1fae5',
        fillStyle: 'hachure',
        strokeWidth: 2,
        roughness: 1,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_vdb_txt',
        type: 'text',
        x: 10,
        y: 28,
        width: 160,
        height: 25,
        text: '📐 Vector DB (Embeddings)',
        fontSize: 13,
        textAlign: 'center',
        strokeColor: '#065f46',
      },
    ],
  },
  {
    id: 'prompt-engine',
    name: 'Prompt 提示词工程流水线',
    nameEn: 'Prompt Pipeline & Templates',
    category: 'ai',
    color: '#ec4899',
    description: '上下文组装、Few-Shot 引导与安全护栏',
    elements: [
      {
        id: 'stencil_prompt_box',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 190,
        height: 80,
        strokeColor: '#ec4899',
        backgroundColor: '#fce7f3',
        fillStyle: 'hachure',
        strokeWidth: 2,
        roughness: 1,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_prompt_txt',
        type: 'text',
        x: 10,
        y: 28,
        width: 170,
        height: 25,
        text: '✨ Prompt Pipeline',
        fontSize: 14,
        textAlign: 'center',
        strokeColor: '#9d174d',
      },
    ],
  },
  // --- 4. UI 界面原型与交互线框 ---
  {
    id: 'ui-browser',
    name: '浏览器视窗原型 (Browser)',
    nameEn: 'Browser Window Frame',
    category: 'ui',
    color: '#64748b',
    description: '标准 Web 浏览器线框与红黄绿三色控件',
    elements: [
      {
        id: 'stencil_win_outer',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 280,
        height: 180,
        strokeColor: '#64748b',
        backgroundColor: '#f8fafc',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 1,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_win_header',
        type: 'line',
        x: 0,
        y: 35,
        width: 280,
        height: 0,
        points: [[0, 0], [280, 0]],
        strokeColor: '#94a3b8',
        strokeWidth: 1.5,
      },
      {
        id: 'stencil_win_dot1',
        type: 'ellipse',
        x: 12,
        y: 12,
        width: 10,
        height: 10,
        strokeColor: '#ef4444',
        backgroundColor: '#fca5a5',
        fillStyle: 'solid',
      },
      {
        id: 'stencil_win_dot2',
        type: 'ellipse',
        x: 28,
        y: 12,
        width: 10,
        height: 10,
        strokeColor: '#f59e0b',
        backgroundColor: '#fde68a',
        fillStyle: 'solid',
      },
      {
        id: 'stencil_win_dot3',
        type: 'ellipse',
        x: 44,
        y: 12,
        width: 10,
        height: 10,
        strokeColor: '#10b981',
        backgroundColor: '#a7f3d0',
        fillStyle: 'solid',
      },
      {
        id: 'stencil_win_url',
        type: 'rectangle',
        x: 65,
        y: 8,
        width: 160,
        height: 18,
        strokeColor: '#cbd5e1',
        backgroundColor: '#ffffff',
        fillStyle: 'solid',
        roundness: { type: 3 },
      },
    ],
  },
  {
    id: 'ui-mobile',
    name: '手机移动端外壳 (Mobile Shell)',
    nameEn: 'Mobile Phone Frame',
    category: 'ui',
    color: '#475569',
    description: '手绘 iOS / Android 手机原型视窗',
    elements: [
      {
        id: 'stencil_phone_outer',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 150,
        height: 260,
        strokeColor: '#475569',
        backgroundColor: '#ffffff',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 1,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_phone_notch',
        type: 'rectangle',
        x: 45,
        y: 6,
        width: 60,
        height: 10,
        strokeColor: '#64748b',
        backgroundColor: '#334155',
        fillStyle: 'solid',
        roundness: { type: 3 },
      },
      {
        id: 'stencil_phone_bar',
        type: 'line',
        x: 45,
        y: 248,
        width: 60,
        height: 0,
        points: [[0, 0], [60, 0]],
        strokeColor: '#94a3b8',
        strokeWidth: 3,
      },
    ],
  },
  {
    id: 'ui-form',
    name: '表单输入与按钮组合',
    nameEn: 'Form Input & Button Set',
    category: 'ui',
    color: '#3b82f6',
    description: '文本输入框与主题提交主按钮',
    elements: [
      {
        id: 'stencil_form_input',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 180,
        height: 38,
        strokeColor: '#94a3b8',
        backgroundColor: '#ffffff',
        fillStyle: 'solid',
        strokeWidth: 1.5,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_form_btn',
        type: 'rectangle',
        x: 0,
        y: 48,
        width: 180,
        height: 38,
        strokeColor: '#2563eb',
        backgroundColor: '#3b82f6',
        fillStyle: 'solid',
        strokeWidth: 1.5,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_form_btntxt',
        type: 'text',
        x: 45,
        y: 57,
        width: 90,
        height: 20,
        text: 'Submit 确定',
        fontSize: 14,
        textAlign: 'center',
        strokeColor: '#ffffff',
      },
    ],
  },
  // --- 5. 流程决策与手绘标记 ---
  {
    id: 'sticky-note',
    name: '灵感便签贴纸 (Sticky Note)',
    nameEn: 'Idea Sticky Note',
    category: 'chart',
    color: '#eab308',
    description: '用于白板头脑风暴或架构备注文档的黄色贴纸',
    elements: [
      {
        id: 'stencil_sticky_bg',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 140,
        height: 130,
        strokeColor: '#ca8a04',
        backgroundColor: '#fef08a',
        fillStyle: 'solid',
        strokeWidth: 1.5,
        roughness: 1,
      },
      {
        id: 'stencil_sticky_txt',
        type: 'text',
        x: 12,
        y: 20,
        width: 116,
        height: 60,
        text: '💡 架构笔记:\n• 核心流转规则\n• 异步解耦落库',
        fontSize: 13,
        strokeColor: '#854d0e',
      },
    ],
  },
  {
    id: 'firewall-shield',
    name: '安全隔离与防火墙',
    nameEn: 'Security WAF / Shield',
    category: 'cloud',
    color: '#e11d48',
    description: '安全合规、访问控制与流量清洗边界',
    elements: [
      {
        id: 'stencil_sec_box',
        type: 'diamond',
        x: 0,
        y: 0,
        width: 150,
        height: 90,
        strokeColor: '#e11d48',
        backgroundColor: '#ffe4e6',
        fillStyle: 'hachure',
        strokeWidth: 2,
        roughness: 1,
      },
      {
        id: 'stencil_sec_txt',
        type: 'text',
        x: 15,
        y: 35,
        width: 120,
        height: 20,
        text: '🛡️ WAF 防护',
        fontSize: 14,
        textAlign: 'center',
        strokeColor: '#9f1239',
      },
    ],
  },
  {
    id: 'badge-status',
    name: '状态印章与标签 (Status Badge)',
    nameEn: 'Status Badge Stamp',
    category: 'chart',
    color: '#10b981',
    description: '用于标记评审状态与演练进度的手绘徽章',
    elements: [
      {
        id: 'stencil_badge_box',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 120,
        height: 36,
        strokeColor: '#059669',
        backgroundColor: '#d1fae5',
        fillStyle: 'solid',
        strokeWidth: 1.5,
        roundness: { type: 3 },
      },
      {
        id: 'stencil_badge_txt',
        type: 'text',
        x: 10,
        y: 8,
        width: 100,
        height: 20,
        text: '✅ PASSED',
        fontSize: 13,
        textAlign: 'center',
        strokeColor: '#065f46',
      },
    ],
  },
];

/**
 * 官方精选社区素材库导览分类
 */
export interface OfficialLibraryCategory {
  id: string;
  name: string;
  nameEn: string;
  queryParam: string;
  description: string;
  icon: string;
  tags: string[];
}

export const OFFICIAL_COMMUNITY_CATEGORIES: OfficialLibraryCategory[] = [
  {
    id: 'cloud-arch',
    name: '云计算与架构 (AWS/GCP/K8s)',
    nameEn: 'Cloud Architecture & K8s',
    queryParam: 'aws',
    description: '涵盖 AWS、Google Cloud、Azure、Kubernetes、Cisco 网络官方标准拓扑素材',
    icon: '☁️',
    tags: ['AWS', 'GCP', 'Kubernetes', 'Docker', 'Azure'],
  },
  {
    id: 'system-design',
    name: '系统设计与微服务 (System Design)',
    nameEn: 'System Design & Software',
    queryParam: 'software',
    description: '微服务架构设计、数据库分片、缓存穿透、消息流与高可用容灾素材',
    icon: '💻',
    tags: ['Microservices', 'Database', 'Redis', 'Kafka'],
  },
  {
    id: 'ui-wireframes',
    name: 'UI 线框与交互组件 (Wireframes)',
    nameEn: 'UI Kits & Wireframing',
    queryParam: 'wireframe',
    description: '移动端 iOS/Android、Web 页面原型、表单控件与线框组件',
    icon: '📱',
    tags: ['Mobile UI', 'Web Kits', 'Forms', 'Components'],
  },
  {
    id: 'flowcharts',
    name: '流程图与业务决策 (Flowcharts)',
    nameEn: 'Flowcharts & Decision Trees',
    queryParam: 'flowchart',
    description: 'UML 类图、泳道图、业务流程与时序交互图元',
    icon: '📊',
    tags: ['UML', 'Swimlane', 'Decision', 'Sequence'],
  },
  {
    id: 'doodles',
    name: '手绘贴纸、便签与表情 (Doodles)',
    nameEn: 'Doodles, Sticky Notes & Badges',
    queryParam: 'stickers',
    description: '丰富多样的手绘高光贴纸、标注箭头、便签卡片与演播印章',
    icon: '🎨',
    tags: ['Stickies', 'Arrows', 'Badges', 'Handdrawn'],
  },
];

/**
 * 将物料图元转为 Excalidraw 原生 LibraryItem 格式
 */
export function stencilsToLibraryItems(stencils: ExcalidrawStencil[]): any[] {
  return stencils.map((s, idx) => ({
    id: s.id || `lib-${Date.now()}-${idx}`,
    status: 'published' as const,
    created: Date.now(),
    name: s.name,
    elements: s.elements || [],
  }));
}

/**
 * 获取全体预置全套素材的 LibraryItem 集合
 */
export function getAllPresetLibraryItems(): any[] {
  return stencilsToLibraryItems(EXCALIDRAW_STENCILS);
}
